#!/bin/bash

export TZ='UTC'
root="/tmp/chkbit"

go run scripts/run_test_prep.go

cd $root/root
mv $root/root/people $root/people
ln -s ../people people
ln -s ../../people/face/office-door.pdf day/friend/office-door.pdf

find -L -type f | wc -l
