#!/bin/bash

export TZ='UTC'
test_dir="/tmp/chkbit"

go run scripts/run_test_prep.go

cd $test_dir/root
mv $test_dir/root/people $test_dir/people
ln -s ../people people
ln -s ../../people/face/office-door.pdf day/friend/office-door.pdf


find -L -type f | wc -l
