#!/bin/bash
set -e

script_dir=$(dirname "$(realpath "$0")")
cd $script_dir/..

echo "# test module"
go test -v .
echo "# test util"
go test -v ./cmd/chkbit/util -count=1

echo "# build"
$script_dir/build

echo "# test files"
go test -v ./scripts -count=1
